### ISSUE TITLE
疑似typo，以及代码风格问题。

### ISSUE THREAD

**Issue by d4x1** [cloudwu/tpp_feedback#1]
P37
Line的构造方法中，应该是`calculate_length`。书中为`calculateLength`。
另外，这段示例代码的风格类似Java。应该考虑使用`calculateLength `而不是`calculate_length `。但不管怎么样，整个示例的风格应该是统一的。两种风格混用。

**Comment by cloudwu** [comment]
我同意。这里出现这个问题，是因为我翻译时拿到的原文版本本身如此。代码我是从原文 copy-paste 的。

刚才核对了英文最新的电子版，已经统一修改成了 `calculateLength` 。 

中文版下一次印刷也争取改过来。
