### ISSUE TITLE
P278 "但再仔细一些盘问后会知道" 有点不太通顺

### ISSUE THREAD

**Issue by dirtysalt** [cloudwu/tpp_feedback#12]
是不是 "但再仔细盘问之后会知道" 或者是 "但再进行一些仔细的盘问后会知道"？

另外不一定是大问题。同一段的最后"没有吸引到真正的魔力"。我觉得应该翻译为"吸引到真正的魔法". 因为在这段之前使用的是 "希望吸引来潜在有效的魔法"。

**Comment by cloudwu** [comment]
我想倒过来应该好点  “但再盘问仔细一些之后会知道" 。

**Comment by dirtysalt** [comment]
是的，也很好。
