### ISSUE TITLE
180页到181页display_case.pie_count是属性而不是方法

### ISSUE THREAD

**Issue by cultmovie** [cloudwu/tpp_feedback#15]
```
if display_case.pie_count > 0
    promise_pie_to_customer()
    display_case.take_pie()
    give_pie_to_customer()
end
```

但在181页里的描述“实际上，当一个服务员执行 display_case.pie_count() 时”，成了方法

**Comment by cloudwu** [comment]
原文是：
> Effectively, when a waiter executes display_case.pie_count(), they copy the value from the display case into their own memory. 

此处是 ruby ，pie_count 是一个 method ，在没有参数的时候，括号可以省略。

**Comment by cultmovie** [comment]
看了下ruby的语法，确实如此
