### ISSUE TITLE
代码问题

### ISSUE THREAD

**Issue by d4x1** [cloudwu/tpp_feedback#2]
Page299 和 Page300 练习6的答案部分，已经说到了：

> ……最好能考虑到，小时的数字只能从0到23，……

这句话的意思很容易让人产生直观的理解：下面的代码是考虑到了以上问题的。但是实际"优化"后的BNF代码示例，写的是`h-tens ::= 0|1`，没有考虑23:01这类的情况。当然应该更严谨些，类似练习7的答案一样，分开考虑。

说这是`错误`比较牵强，但是不严谨。

**Comment by cloudwu** [comment]
英文原文是：

> A better definition of hour and minute would take into account that an hours can only be from 00 to 23, and a minute from 00 to 59:

下面也写的是 `h-tens ::= 0|1`

我赞同或许加上 `0|1|2` 可能更好，但同时感觉翻译时不宜过度发挥。而且后面一部分的 BNF 并没有处理 am|pm  的情况，如果要补完整需要添加很多内容。
