### ISSUE TITLE
P148 拼写错误，不再须要 -> 不再需要

### ISSUE THREAD

**Issue by zhangjie2012** [cloudwu/tpp_feedback#7]
148 页，第五章 宁弯不折

*时间流是异步集合* 的第二段

我们不再 _须要_  将时间视为必须要管理的东西。 => 需要

**Comment by cloudwu** [comment]
我觉得此处用 “须要” 并无不妥。

**Comment by zhangjie2012** [comment]
好吧，按照一般的阅读习惯，会感觉不太舒服

**Comment by cloudwu** [comment]
btw, 此处我的原译文为 “需要”， 改成 “须要” 是经过了编辑的校对。我猜想 “须要” 更符合《现代汉语》的标准。
